<?php
$this->form->prepare();
$this->form->setAttribute('action', $this->url('catalogo', ['action' => 'guardar']))
        ->setAttribute('class', 'form-horizontal')
        ->setAttribute('role', 'form');
?>
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->titulo ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <a class = 'btn btn-default btn-xs' role = 'button'
                       href="<?= $this->url('catalogo', ['action' => 'index']); ?>"><-- Volver</a>
                </p>
                <?= $this->form()->openTag($this->form) ?>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('categoria')) ?>
                    <div class="col-sm-5">
                        <?= $this->formSelect($this->form->get('categoria')) ?>
                    </div>
                    <div><?= $this->formElementErrors($this->form->get('categoria')) ?></div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('descripcion')) ?>
                    <div class="col-sm-5">
                        <?= $this->formInput($this->form->get('descripcion')) ?>
                    </div>
                    <div><?= $this->formElementErrors($this->form->get('descripcion')) ?></div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('precio')) ?>
                    <div class="col-sm-5">
                        <?= $this->formInput($this->form->get('precio')) ?>
                    </div>
                    <div><?= $this->formElementErrors($this->form->get('precio')) ?></div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('cantidad')) ?>
                    <div class="col-sm-5">
                        <?= $this->formInput($this->form->get('cantidad')) ?>
                    </div>
                    <div><?= $this->formElementErrors($this->form->get('cantidad')) ?></div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-5">
                        <?= $this->formSubmit($form->get('send')) ?>
                    </div>
                </div>
                <?= $this->formHidden($form->get('id')) ?>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>