<?= $this->doctype() ?>

<html lang="en">
    <head>
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/justified-nav.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
        ?>
    </head>
    <body>

        <div class="container">
            <div class="masthead">
                <h3 class="text-muted">Zend Framework &nbsp;Skeleton Application</h3>
                <nav>
                    <ul class="nav nav-justified">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                        <li><a href="<?= $this->url('usuarios') ?>">Usuarios</a></li>
                        <li><a href="<?= $this->url('cursos') ?>">Curso</a></li>
                        <li><a href="#">Contacto</a></li>
                        <li><a href="#">Login</a></li>
                    </ul>
                </nav>
            </div>
            <hr>
            <div class="row">
                <?= $this->layout()->content; ?>
            </div>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>

        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>