<div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
        <div class="panel-heading"><?= $this->titulo ?></div>

        <div class="panel-body">
            <p>Hoy es: <?= $this->fecha ?></p>
            <table class="table table-striped table-hover" style="width:800px; text-align:left">
                <thead>
                    <tr>
                        <th>Cursos</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->cursos as $curso): ?>
                        <tr>
                            <td><?= $curso ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>