<?php
$this->form->prepare();
$form->setAttribute('action', $this->url('login', ['action' => 'autenticar']));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->setAttribute('role', 'form');
?>
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->titulo ?></h3>
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($this->form) ?>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('email')) ?>
                    <div class="col-sm-5">
                        <?= $this->formInput($this->form->get('email')) ?>
                    </div>
                    <div><?= $this->formElementErrors($this->form->get('email')) ?></div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('password')) ?>
                    <div class="col-sm-5">
                        <?= $this->formInput($this->form->get('password')) ?>
                    </div>
                    <div><?= $this->formElementErrors($this->form->get('password')) ?></div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-5">
                        <?= $this->formSubmit($form->get('send')) ?>
                    </div>
                </div>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>