<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta()->setCharset('UTF-8') ?>
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <?php echo $this->headStyle() ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo.png') ?>" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                        <li><a href="<?= $this->url('usuarios') ?>">Usuarios</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="header">
            <h3>Men&uacute; y cabecera de p&aacute;gina</h3>
        </div>
        <div class="content">
            <?php if ($this->layout()->tiempoCarga): ?>
                <div class="alert alert-success" role="alert">
                    <?php echo $this->layout()->tiempoCarga ?>
                </div>
            <?php endif; ?>
            <?php echo $this->content; ?>
        </div>
        <div class="footer">
            <h3>&copy; 2005 - 2016 por Formaci&oacute;n BDI.</h3>
        </div>
    </body>
</html>